In [1]:
import numpy as np

In [2]:
arr = np.array([2,1,5,3,7,4,6,8])

In [3]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [8]:
(a, b)

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [10]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
print(a, b)

[1 2 3 4] [5 6 7 8]


In [12]:
a.size

4

In [13]:
b.size

4

In [15]:
b = np.array([[1,1],[2,2]])

In [16]:
print(b)

[[1 1]
 [2 2]]


In [17]:
#sum the rows of b above
b.sum(axis=0)

array([3, 3])

In [18]:
#sum the columns 
b.sum(axis=1)

array([2, 4])

In [19]:
data = np.array([1.0, 2.0])

In [20]:
data * 1.6

array([1.6, 3.2])